name: Build Devious Editor Remastered

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v5.5.3
          combine: false
          export-pdb: true
